# Generated by Django 2.2.3 on 2019-08-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CPUInfo',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.BaseModel')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('mobile', 'Mobile'), ('laptop', 'Laptop'), ('desktop', 'Desktop')], max_length=32)),
                ('core', models.SmallIntegerField()),
                ('thread', models.SmallIntegerField()),
                ('base_freq', models.FloatField()),
                ('max_freq', models.FloatField()),
                ('cache', models.SmallIntegerField()),
            ],
            bases=('products.basemodel',),
        ),
        migrations.CreateModel(
            name='RAMInfo',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.BaseModel')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(choices=[('ddr4', 'DDR4'), ('ddr3', 'DDR3'), ('ddr3l', 'DDR3L')], max_length=16)),
                ('use_type', models.CharField(choices=[('laptop', 'RAM Laptop'), ('desktop', 'RAM DESKTOP')], max_length=16)),
                ('memory_size', models.SmallIntegerField(null=True)),
                ('bus', models.CharField(max_length=16, null=True)),
                ('timing', models.SmallIntegerField(null=True)),
            ],
            bases=('products.basemodel',),
        ),
        migrations.CreateModel(
            name='VGAInfo',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.BaseModel')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255, null=True)),
                ('use_type', models.CharField(choices=[('laptop', 'RAM Laptop'), ('desktop', 'RAM DESKTOP')], max_length=16)),
                ('core', models.SmallIntegerField()),
                ('base_clock', models.SmallIntegerField()),
                ('boost_clock', models.SmallIntegerField()),
            ],
            bases=('products.basemodel',),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.BaseModel')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=16)),
                ('service_tag', models.CharField(blank=True, max_length=16)),
                ('screen_size', models.FloatField()),
                ('screen_type', models.CharField(max_length=16)),
                ('screen_resolution', models.CharField(choices=[('hd', 'HD (1280x720)'), ('full_hd', 'Full HD (1920x1080)'), ('hd+', 'HD+ (1600x900)'), ('2k', '2K (2560x1440)'), ('4k', 'UHD 4K (3840x2160)')], max_length=16)),
                ('os', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=16)),
                ('weight', models.CharField(max_length=16)),
                ('cpu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='products.CPUInfo')),
                ('ram_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='products.RAMInfo')),
                ('vga_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='products.VGAInfo')),
            ],
            bases=('products.basemodel',),
        ),
    ]
