# Generated by Django 2.2.4 on 2019-08-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vgainfo',
            name='features',
            field=models.TextField(null=True, verbose_name='Tính năng'),
        ),
        migrations.AlterField(
            model_name='vgainfo',
            name='memory_type',
            field=models.CharField(max_length=128, null=True, verbose_name='Loại bộ nhớ'),
        ),
    ]
