# Generated by Django 2.2.3 on 2019-08-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190825_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='cover',
            field=models.ImageField(height_field=200, null=True, upload_to='', width_field=200),
        ),
    ]
