# Generated by Django 2.2.4 on 2019-08-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190826_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpuinfo',
            name='base_freq',
        ),
        migrations.RemoveField(
            model_name='cpuinfo',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='cpuinfo',
            name='cache',
        ),
        migrations.RemoveField(
            model_name='cpuinfo',
            name='max_freq',
        ),
        migrations.RemoveField(
            model_name='cpuinfo',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='cpuinfo',
            name='type',
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='announce_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='clock_rate',
            field=models.CharField(max_length=128, null=True, verbose_name='Xung nhịp (MHz)'),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='code_name',
            field=models.CharField(max_length=128, null=True, verbose_name='Tên mã'),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='die_size',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='features',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='gpu',
            field=models.CharField(max_length=255, null=True, verbose_name='Đồ họa tích hợp'),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='l1_cache',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='l2_cache',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='l3_cache',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='manufacture',
            field=models.CharField(max_length=255, null=True, verbose_name='Hãng'),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='max_temp',
            field=models.CharField(max_length=64, null=True, verbose_name='Nhiệt độ tối đa'),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='power_consumption',
            field=models.CharField(max_length=128, null=True, verbose_name='Công suất tiêu thụ (W)'),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='reference_link',
            field=models.CharField(max_length=512, null=True, verbose_name='Link tham khảo'),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='series',
            field=models.CharField(max_length=255, null=True, verbose_name='Dòng'),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='sixty_four_bit',
            field=models.CharField(max_length=128, null=True, verbose_name='64 Bit'),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='socket',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='technology',
            field=models.CharField(max_length=64, null=True, verbose_name='Công nghệ'),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='threads',
            field=models.SmallIntegerField(null=True, verbose_name='Số luồng'),
        ),
        migrations.AddField(
            model_name='cpuinfo',
            name='transistor_count',
            field=models.CharField(max_length=128, null=True, verbose_name='Số lượng bóng bán dẫn'),
        ),
        migrations.AlterField(
            model_name='cpuinfo',
            name='core',
            field=models.SmallIntegerField(null=True, verbose_name='Số lõi'),
        ),
    ]
