# Generated by Django 2.2.3 on 2019-08-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_laptop_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
